version: "3.8"
services:
  update_check:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: update_check
    image: update_check:latest
    network_mode: host
    volumes:
      - ./config.json:/update_check/config.json
      - /run/dietpi:/run/dietpi
    environment:
      - TZ=UTC
    restart: always


